# Generated by Django 3.1 on 2020-08-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pwd',
        ),
    ]
