# Generated by Django 3.1 on 2020-08-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_login', '0004_auto_20200821_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='leaves',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='projects',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='status',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='trainings',
            field=models.TextField(default=''),
        ),
    ]
