# Generated by Django 3.1 on 2020-08-22 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('d_login', '0007_auto_20200821_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataHistory',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('updated_on', models.DateTimeField(default=datetime.datetime.now)),
                ('t_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('trainings', models.TextField(default='')),
                ('projects', models.TextField(default='')),
                ('status', models.CharField(default='', max_length=250)),
                ('leaves', models.CharField(default='', max_length=100)),
            ],
            options={
                'unique_together': {('updated_on', 'user')},
            },
        ),
    ]
