# Generated by Django 3.1 on 2020-09-02 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('d_login', '0009_auto_20200822_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project1', models.TextField(default='')),
                ('project2', models.TextField(default='')),
                ('project3', models.TextField(default='')),
                ('project4', models.TextField(default='')),
                ('project5', models.TextField(default='')),
                ('project6', models.TextField(default='')),
                ('project7', models.TextField(default='')),
                ('project8', models.TextField(default='')),
                ('project9', models.TextField(default='')),
                ('project10', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
