# Generated by Django 3.1 on 2020-09-02 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('d_login', '0011_auto_20200902_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprojectdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprojectdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
