# Generated by Django 3.1 on 2020-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_login', '0014_auto_20200902_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectdata',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
